In [ ]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)
a = quicksort([2,3,5,6,8,4,4,6,1,85,7,4,5,6,9,4])
print(quicksort([2,3,5,6,8,4,4,6,1,85,7,4,5,6,9,4]))

[1, 2, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 8, 9, 85]


In [ ]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    flag = arr[1]
    left = [x for x in arr if x < flag]
    middle = [x for x in arr if x == flag]
    right = [x for x in arr if x > flag]
    return quicksort(left) + middle + quicksort(right)
a = quicksort([2,3,5,6,8,4,4,6,1,85,7,4,5,6,9,4])
print(quicksort([2,3,5,6,8,4,4,6,1,85,7,4,5,6,9,4]))

[1, 2, 3, 4, 4, 4, 4, 5, 5, 6, 6, 6, 7, 8, 9, 85]


In [ ]:
x = 3
print( x, type(x))
print (x + 1)   
print (x - 1 )  
print (x * 2 )  
print (x ** 2)  

3 <class 'int'>
4
2
6
9


In [ ]:
len("hello")

5

In [ ]:
hw12 = '%s %s %d' % ("hello", "world", 12.5) 
print(hw12)

hello world 12


In [ ]:
s = "hEllo"
print (s.title())  
print (s.upper())   
print (s.rjust(7))   
print (s.center(7))   
print (s.replace('l', '(ell)'))  
                               
print ('world '.strip()) 

Hello
HELLO
  hEllo
 hEllo 
hE(ell)(ell)o
world


In [ ]:
xs = [3, 1, 2]   
print (xs,";",xs[2])
print (xs[-1])    

[3, 1, 2] ; 2
2


In [ ]:
print (xs) 
xs[2] = 'foo' 
print (xs) 
x = xs.pop()
print (x,";",xs)
xs.append('bar') 
xs.append('bar')
print (xs)

[3, 1, 'foo', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar']
[3, 1, 'foo', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar']
bar ; [3, 1, 'foo', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar']
[3, 1, 'foo', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar']


In [ ]:
nums = range(5)    
num=list()
for i in nums:
    num.append(i)
print(num)
print (num[2:4])   
print (num[2:] )   
print (num[:2] )   
print (num[:]  )   
print (num[:-1])   
num[2:4] = [8, 9]
print (num     )   

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

cat
dog
monkey


In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

[0, 4, 16]


In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  
print (d['cat'])    
print ('cat' in d)

cute
True


In [ ]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print (d['fish'] )


wet


In [ ]:
print (d.get('monkey', 'N/A'))
print (d.get('fish', 'N/A')) 

N/A
wet


In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

{0: 0, 2: 4, 4: 16}


In [ ]:
animals = {'cat', 'dog'}
print ('cat' in animals) 
print ('fish' in animals)


True
False


In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: fish


In [ ]:
from math import sqrt
print ({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


In [ ]:
d = {(x, x + 1): x for x in range(10)} 
print(d)
t = (5, 6)       
print (type(t))
print (d[t])      
print (d[(1, 2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
<class 'tuple'>
5
1


In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print (sign(x))

negative
zero
positive


In [ ]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s' % name.upper())
    else:
        print ('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  

    # Instance method
    def greet(self, loud=False):
        if loud:
            print ('HELLO, %s!' % self.name.upper())
        else:
            print ('Hello, %s' % self.name)

g = Greeter('Fred')  
g.greet()            
g.greet(loud=True)   

Hello, Fred
HELLO, FRED!


In [5]:
import numpy as np
a = np.array([1, 2, 3])
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print (a) 
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print (b)
print (b.shape, b.dtype, b.size, b.ndim)                   
print (b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3) int64 6 2
1 2 4


In [11]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)
b = a[0:2, 1:3]
print (b)
print (a[0, 1]  )
b[0, 0] = 77    
print (a[0, 1] )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [14]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


In [27]:
a = np.array([[1,2], [3, 4], [5, 6]])
print (a)
b = a[[0, 1, 2], [0, 1, 1]]
b[0] = 9
print (a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [33]:

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print (a)
print("#######")
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print (a[np.arange(4), b] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
#######
[ 1  6  7 11]


In [43]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print (a)

[[101   2   3]
 [  4   5 106]
 [107   8   9]
 [ 10 111  12]]


In [46]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [67]:
x = np.array([1, 2.0])  
y = np.array([1.0, 2])  
z = np.array([1.1, 2.0], dtype=np.int64) 

print (x.dtype, y.dtype, z.dtype)

float64 float64 int64


In [73]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print("+")
print (x + y)
print (np.add(x, y))
print("-")
print (x - y)
print (np.subtract(x, y))
print("*")
print (x * y)
print (np.multiply(x, y))
print(":")
print (x / y)
print (np.divide(x, y))
print("can bac 2")
print (np.sqrt(x))

+
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
-
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
*
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
can bac 2
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [76]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print (v.dot(w))
print (np.dot(v, w))
print (x.dot(v))
print (np.dot(x, v))

219
219
[29 67]
[29 67]


In [77]:
x = np.array([[1,2],[3,4]])

print (np.sum(x)  )
print (np.sum(x, axis=0) )
print (np.sum(x, axis=1) )

10
[4 6]
[3 7]
